name: CI

on:
  push:
    branches:
      - bwmac/orca-202/ghcr_cicd

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: true
        tags: ghcr.io/${{ github.repository.toLowerCase() }}/my-image:ci_test
